# Generated by Django 4.2.23 on 2025-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ENGINEER', 'Engineer'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=20, unique=True)),
                ('view_sources', models.BooleanField(default=False)),
                ('view_tables', models.BooleanField(default=False)),
                ('view_files', models.BooleanField(default=False)),
                ('view_schemas', models.BooleanField(default=False)),
                ('run_etl', models.BooleanField(default=False)),
                ('view_data', models.BooleanField(default=False)),
                ('manage_users', models.BooleanField(default=False)),
                ('view_db_credentials', models.BooleanField(default=False)),
            ],
        ),
    ]
