# Generated by Django 4.2.23 on 2025-09-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rolepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
