# Generated by Django 5.2.1 on 2025-05-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=50)),
                ('db_role', models.CharField(max_length=50)),
                ('host1', models.CharField(max_length=255)),
                ('port1', models.IntegerField()),
                ('database1', models.CharField(max_length=255)),
                ('username1', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Database Credential',
                'verbose_name_plural': 'Database Credentials',
                'db_table': 'ETL_DATABASE_CRED',
            },
        ),
        migrations.CreateModel(
            name='SourceFileInfo',
            fields=[
                ('SRCFILE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATASRC_ID', models.IntegerField()),
                ('SRC_DIRECTORY', models.CharField(blank=True, max_length=255, null=True)),
                ('SRC_FILENAME', models.CharField(blank=True, max_length=255, null=True)),
                ('TGT_DATABASE', models.CharField(blank=True, max_length=64, null=True)),
                ('TGT_TABLENAME', models.CharField(blank=True, max_length=64, null=True)),
                ('SRCLAYOUT_ID', models.IntegerField()),
                ('TRGLAYOUT_ID', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Source File Information',
                'verbose_name_plural': 'Source File Information',
                'db_table': 'ETL_SRCFILE_INFO',
            },
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('SOURCE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SOURCE_NM', models.CharField(blank=True, max_length=64, null=True)),
                ('SOURCE_TYP', models.CharField(blank=True, max_length=64, null=True)),
                ('USERID', models.CharField(blank=True, max_length=64, null=True)),
                ('USERPSWRD', models.CharField(blank=True, max_length=64, null=True)),
                ('EXTRCT_MTHD', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Source Information',
                'verbose_name_plural': 'Source Information',
                'db_table': 'ETL_SOURCE_INFO',
            },
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('SRCTBL_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATASRC_ID', models.IntegerField()),
                ('SRC_DATABASE', models.CharField(blank=True, max_length=64, null=True)),
                ('SRC_SCHEMA', models.CharField(blank=True, max_length=64, null=True)),
                ('SRC_TABLENAME', models.CharField(blank=True, max_length=64, null=True)),
                ('TGT_DATABASE', models.CharField(blank=True, max_length=64, null=True)),
                ('TGT_SCHEMA', models.CharField(blank=True, max_length=64, null=True)),
                ('TGT_TABLENAME', models.CharField(blank=True, max_length=64, null=True)),
                ('SRCLAYOUT_ID', models.IntegerField()),
                ('TRGLAYOUT_ID', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Table Information',
                'verbose_name_plural': 'Table Information',
                'db_table': 'ETL_TABLE_INFO',
            },
        ),
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('SRCTBL_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COLUMN_SEQ', models.IntegerField()),
                ('SRC_TRG_IND', models.CharField(max_length=3)),
                ('SCHEMA_NM', models.CharField(blank=True, max_length=64, null=True)),
                ('TABLE_NM', models.CharField(blank=True, max_length=64, null=True)),
                ('COLUMN_NM', models.CharField(blank=True, max_length=64, null=True)),
                ('DATA_TYPE', models.CharField(blank=True, max_length=64, null=True)),
                ('XFRMTN', models.CharField(blank=True, max_length=128, null=True)),
                ('PRIMARY_KEY', models.CharField(blank=True, max_length=1, null=True)),
                ('DEFAULT_VAL', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Table Schema',
                'verbose_name_plural': 'Table Schemas',
                'db_table': 'ETL_TBL_SCHEMA',
                'unique_together': {('SRCTBL_ID', 'COLUMN_SEQ', 'SRC_TRG_IND')},
            },
        ),
    ]
