# Generated by Django 4.2.23 on 2025-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableinfo',
            name='REF_FRQNCY',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='SRCTBL_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='SRC_DATABASE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='SRC_SCHEMA',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='SRC_TABLENAME',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='TGT_DATABASE',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='TGT_SCHEMA',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tableinfo',
            name='TGT_TABLENAME',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='ExecutionTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXECUTION_DT', models.DateField()),
                ('SRCTBL_ID', models.IntegerField()),
                ('COMPLETE_TRACK', models.CharField(default='N', max_length=1)),
                ('REC_LOAD_COUNT', models.BigIntegerField(blank=True, null=True)),
                ('LAST_EXEC_DT', models.DateField(default='2000-01-01')),
                ('NEXT_EXEC_DT', models.DateField(default='2099-12-31')),
            ],
            options={
                'verbose_name': 'Execution Track',
                'verbose_name_plural': 'Execution Tracks',
                'db_table': 'EXECUTION_TRACK',
                'unique_together': {('EXECUTION_DT', 'SRCTBL_ID')},
            },
        ),
    ]
