# Generated by Django 4.2.23 on 2025-06-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0002_tableinfo_ref_frqncy_alter_tableinfo_srctbl_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasecred',
            old_name='database1',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='databasecred',
            old_name='host1',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='databasecred',
            old_name='port1',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='databasecred',
            old_name='username1',
            new_name='username',
        ),
    ]
