# Generated by Django 4.2.23 on 2025-06-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0003_rename_database1_databasecred_database_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasecred',
            old_name='password1',
            new_name='password',
        ),
    ]
