# Generated by Django 4.2.23 on 2025-06-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0004_rename_password1_databasecred_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseCred',
            new_name='database_cred',
        ),
        migrations.RenameModel(
            old_name='ExecutionTrack',
            new_name='execution_track',
        ),
        migrations.RenameModel(
            old_name='SourceInfo',
            new_name='source_info',
        ),
        migrations.RenameModel(
            old_name='SourceFileInfo',
            new_name='srcfile_info',
        ),
        migrations.RenameModel(
            old_name='TableInfo',
            new_name='srctbl_info',
        ),
        migrations.RenameModel(
            old_name='TableSchema',
            new_name='table_schema',
        ),
    ]
