# Generated by Django 4.2.23 on 2025-06-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0005_rename_databasecred_database_cred_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='database_cred',
            table='database_cred',
        ),
        migrations.AlterModelTable(
            name='execution_track',
            table='execution_track',
        ),
        migrations.AlterModelTable(
            name='source_info',
            table='source_info',
        ),
        migrations.AlterModelTable(
            name='srcfile_info',
            table='srcfile_info',
        ),
        migrations.AlterModelTable(
            name='srctbl_info',
            table='srctbl_info',
        ),
        migrations.AlterModelTable(
            name='table_schema',
            table='table_schema',
        ),
    ]
