# Generated by Django 4.2.23 on 2025-08-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0006_alter_database_cred_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srctbl_info',
            name='SRCLAYOUT_ID',
        ),
        migrations.RemoveField(
            model_name='srctbl_info',
            name='TRGLAYOUT_ID',
        ),
        migrations.AlterField(
            model_name='srctbl_info',
            name='SRCTBL_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
