# Generated by Django 4.2.23 on 2025-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0007_remove_srctbl_info_srclayout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='srctbl_info',
            name='SELECT_QUERY',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
