# Generated by Django 4.2.23 on 2025-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0008_srctbl_info_select_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='srctbl_info',
            name='FILTER_COND',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
