# Generated by Django 4.2.23 on 2025-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0009_srctbl_info_filter_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='srctbl_info',
            name='RECON_REQ',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='srctbl_info',
            name='FILTER_COND',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
