# Generated by Django 4.2.23 on 2025-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0010_srctbl_info_recon_req_alter_srctbl_info_filter_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='srctbl_info',
            name='ACTIVE_IND',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='srctbl_info',
            name='LOAD_TYPE',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='srctbl_info',
            name='TRG_TABLE_SFX',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
