# Generated by Django 4.2.23 on 2025-09-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_system', '0013_alter_useraccess_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccess',
        ),
    ]
